# Generated by Django 5.1.3 on 2024-12-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0004_rename_recruiter_job_company_jobseeker_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_job_seeker',
            new_name='is_jobseeker',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='recruiter',
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('recruiter', 'title')},
        ),
    ]
