# Generated by Django 5.1.3 on 2024-12-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0005_rename_is_job_seeker_customuser_is_jobseeker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='recruiter',
            new_name='company',
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('company', 'title')},
        ),
    ]
