# Generated by Django 5.1.3 on 2024-12-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0006_rename_recruiter_job_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_jobseeker',
            new_name='is_job_seeker',
        ),
    ]
