# Generated by Django 5.1.3 on 2024-12-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0007_rename_is_jobseeker_customuser_is_job_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
