# Generated by Django 5.1.3 on 2024-12-09 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0010_alter_recruiters_user_alter_jobseeker_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='miniapp.jobseeker'),
        ),
    ]
