# Generated by Django 5.1.3 on 2024-12-09 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0011_alter_application_jobseeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to='miniapp.recruiters'),
        ),
    ]
