# Generated by Django 5.1.3 on 2024-12-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
