# Generated by Django 5.1.3 on 2024-12-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0016_profile_company_name_profile_phone_profile_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='recruiter',
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('recruiter', 'title')},
        ),
    ]
