# Generated by Django 5.1.3 on 2024-12-10 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0017_rename_company_job_recruiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to='miniapp.recruiters', verbose_name='Company'),
        ),
    ]
