# Generated by Django 5.1.3 on 2024-12-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0018_alter_job_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('recruiter', 'Recruiter')], max_length=20),
        ),
    ]
