# Generated by Django 5.1.3 on 2024-12-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0019_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('jobseeker', 'JobSeeker'), ('recruiter', 'Recruiters')], max_length=20),
        ),
    ]
