# Generated by Django 5.1.3 on 2024-12-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0023_alter_application_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
    ]
