# Generated by Django 5.1.3 on 2024-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0027_remove_application_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiters',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='recruiters',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiters',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
